#------------------------------------------------------
#                      Cabeçalho
#------------------------------------------------------
# Nome da action e quando ela é disparada
name: Fluxo para construcao e publicacao do container
on: [push, pull_request]

#------------------------------------------------------
#                      Variáveis
#------------------------------------------------------
env:
  tika_version: '1.25'

#------------------------------------------------------
#                   Início dos jobs
#------------------------------------------------------
jobs:

#------------------------------------------------------
#              job 01 - Lint do Dockerfile
#------------------------------------------------------
  lint:
    name: Lint do Dockerfile
    runs-on: ubuntu-18.04
    steps:
#---------------------step 01-01-----------------------
      - name: Checkout
        uses: actions/checkout@v2
#---------------------step 01-02-----------------------
      - name: lint
        uses: luke142367/Docker-Lint-Action@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target: Dockerfile

#------------------------------------------------------
#              job 04 - Scan da imagem
#------------------------------------------------------
  build:
    name: Scan da Imagem
    runs-on: ubuntu-18.04
    steps:
#---------------------step 04-01-----------------------
      - name: Checkout code
        uses: actions/checkout@v2
#---------------------step 04-02-----------------------
      - name: Build an image from Dockerfile
        run: |
          docker build -t tika:${{ github.sha }} .
#---------------------step 04-03-----------------------
      - name: Scanear Imagem com Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'tika:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'